# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBookStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=24, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='unactivatedaccount',
            name='name',
            field=models.CharField(default='', max_length=24, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='logisticsorder',
            name='logistics_token',
            field=models.CharField(default=b'mWycLtgdEeeFLqzgEJ3fJg==', editable=False, max_length=24, verbose_name='物流token'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='deadline',
            field=models.DateTimeField(default=1512300729.7737586, verbose_name='支付期限'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_token',
            field=models.UUIDField(default=b'mWwTdNgdEeeNcqzgEJ3fJg==', editable=False, verbose_name='支付token'),
        ),
        migrations.AlterField(
            model_name='unactivatedaccount',
            name='activation_token',
            field=models.CharField(default=b'mWvYuNgdEeehfqzgEJ3fJg==', editable=False, max_length=24, verbose_name='邮箱验证token'),
        ),
    ]
