# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:34
from __future__ import unicode_literals

import PublicModule.ImageStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBookStore', '0003_auto_20171204_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.ImageField(storage=PublicModule.ImageStorage.ImageStorage(), upload_to='book_cover', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='logisticsorder',
            name='logistics_token',
            field=models.CharField(default='8BcvSthgEee7lazgEJ3fJg==', editable=False, max_length=24, verbose_name='物流token'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='deadline',
            field=models.DateTimeField(default=1512329651.456075, verbose_name='支付期限'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_token',
            field=models.UUIDField(default='8BaS7thgEeeGiKzgEJ3fJg==', editable=False, verbose_name='支付token'),
        ),
        migrations.AlterField(
            model_name='unactivatedaccount',
            name='activation_token',
            field=models.CharField(default='8BZEwNhgEeeDwazgEJ3fJg==', editable=False, max_length=24, verbose_name='邮箱验证token'),
        ),
    ]
