# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBookStore', '0005_auto_20171205_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsorder',
            name='logistics_token',
            field=models.CharField(default='mbAkmNmqEeeB7KzgEJ3fJg==', editable=False, max_length=24, verbose_name='物流token'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='deadline',
            field=models.DateTimeField(default=1512471240.4154773, verbose_name='支付期限'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_token',
            field=models.UUIDField(default='ma85lNmqEeeINazgEJ3fJg==', editable=False, verbose_name='支付token'),
        ),
        migrations.AlterField(
            model_name='unactivatedaccount',
            name='activation_token',
            field=models.CharField(default='ma7X2NmqEee2WKzgEJ3fJg==', editable=False, max_length=24, verbose_name='邮箱验证token'),
        ),
        migrations.AlterField(
            model_name='usedbook',
            name='shopping_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineBookStore.ShoppingOrder', verbose_name='购物订单'),
        ),
    ]
